services:
  db:
    image: mysql:8.0
    container_name: atec_secretaria_DB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: atec_secretaria
      MYSQL_USER: tpsi_user
      MYSQL_PASSWORD: tpsi_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: